### ISSUE TITLE
Can't gain exp at all after using Advanced Enchanting Table

### ISSUE THREAD

**Issue by penguinmayhem** [Epoxide-Software/Enchanting-Plus#66] opened 2017-04-07 20:27 UTC
Used Advanced Enchanting Table.  Brought down to level 16. Found I couldn't gain any exp whatsoever even though I was picking up a lot of it.  Killing mobs, mining, cooking, nothing.  No levels, the exp bar doesn't even fill up.  Even giving myself exp bottles does nothing.

I am running Enchanting Plus 4.1.0.115 alongside EnderIO 3.1.156

Killing myself fixed it.  Still not sure what's wrong.

**Comment by Revvilo** [comment] 2017-04-23 23:26
It's caused by repairing items, once your XP Bar reaches nothing, instead of bringing you down a level, the XP Bar's NBT value (inside your player .dat file) goes into the negatives, producing this weird glitch of not being able to get experience.
Serious bug IMO.

**Comment by Revvilo** [comment] 2017-04-24 01:12
I did a little digging and found that the mod is using `player.addExperience(-cost)` to do the experience adjusting, but according to [this](http://www.minecraftforge.net/forum/topic/18382-172-draw-experience-from-the-player-every-few-ticks/) it might not be the right thing to do.
Considering I'm a mere java fetus and have no idea how much of it works I might be wayyy off, but if I don't try I don't learn.

**Comment by darkhax** [comment] 2018-09-17 06:59
This issue has been fixed in the 1.12.2 version of the mod.

**Closed by darkhax** 2018-09-17 06:59 UTC
Labels: Old, bug
